mq:
  aggr30minQueue: "common-email-alert-aggr-30m-queue-prd"
  aggr1hourQueue: "common-email-alert-aggr-1h-queue-prd"
  aggr2hourQueue: "common-email-alert-aggr-2h-queue-prd"
  aggr4hourQueue: "common-email-alert-aggr-4h-queue-prd"
  aggr8hourQueue: "common-email-alert-aggr-8h-queue-prd"
  aggr12hourQueue: "common-email-alert-aggr-12h-queue-prd"
  aggr24hourQueue: "common-email-alert-aggr-24h-queue-prd"
  aggrErrorQueue: "common-email-alert-aggr-error-queue-prd"
  standardErrorQueue: "common-email-alert-queue-prd"
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  clientId: "bbe429eec5ad44d4baaca37a30061bd9" #ClientID and Secret of "common-email-alert-aggr-30m-queue-prd"
  clientSecret: "![JuseUg/tD2rjAgR1T1JwhUItSHk9OrgERpwUl6UoiEmoXpjNnoj8fA==]"
  
aggr:
  groupSize: "500"
  
timeout:
  aggr30minQueue: "30"
  aggr1hourQueue: "60"
  aggr2hourQueue: "120"
  aggr4hourQueue: "240"
  aggr8hourQueue: "480"
  aggr12hourQueue: "720"
  aggr24hourQueue: "1440"
  
app:
  name: "common-email-alert-aggregator"
  businessId: "12345678"
  
email:
  to: "a.thammyshetty@shell.com"
  
mule:
  env: "prod"
  
subscriber:
  fetchsize : "10"
  frequency : "1000"
  startdelay: "0"

  
